language: java

before_install: |
  if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    export JDK_NAME="JDK 8 Update 73"
    export JDK_FILENAME="jdk-8u73-macosx-x64.dmg"
    export JDK_DOWNLOAD_URL="http://download.oracle.com/otn-pub/java/jdk/8u73-b02/$JDK_FILENAME"
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "$JDK_DOWNLOAD_URL" -O "$JDK_FILENAME"
    hdiutil mount "$JDK_FILENAME"
    sudo installer -pkg "/Volumes/$JDK_NAME/$JDK_NAME.pkg" -target LocalSystem
    java -Xmx32m -version
    javac -J-Xmx32m -version
  fi

matrix:
  include:
    - os: osx
      script: ./gradlew clean :client:jfxNative
      deploy:
        provider: releases
        api_key:
          secure: "kaF5Z4L9NjVqzjdY3GbyGMV2NgYLygkAf99qIPSrm3viUyNBmK+rVmZQuIA8y930fRPt7m0I2KmC1qIsAyVidiDX4MDFHg1b1m4BCwg63Z8s489E66wwOVOIuu+pOxiDONz4nyWTDHUQf/KQUnD3fzTg9nCDL69AYy/AF3v8C4T/GZyb9nLChnR5iM08SA8/rznlosQi6YDCebjX3oVY3jgbF2pZtuMDsznuDE4rEuXKXkK6Le+sp2yZtHjXnwOhBFiFWURhqnps1bJ8sKadaZxhhlcHdtB6frRjU7eNZDguq9cse20ayqpDOWZ47jL3GYZQ993blTFolSRcIb4uj+NJNJc0ujd7QOU+GVgir38T544m2/gXsn3emrlGVI/Jt08yv5QS/3+dXo7dW9z//0mWNucPiQeYIOfMG3C9LukYGKHv7Hy/nPDfsd3EiiwXgrzd85lAKLn6zvVNY1uUuDLxNR6X1Jru6trwTnJ1rX4r5+iVVOS0NJI6bYkoo5OwyZtG3E+McT6JfKZIscSo04Mwvxq2Wh/en03i5y41mrs6SEeBWSnEmIkx+hR2lkNeOIvU8JnPN5OIAxBiadQ713g6jlw1PwTV5hW+0rdetXkVAL1jtLgi9pnYnT8Q3Ayp2Iwltg1d2ClHwh26V5femrXEmDFJpNfmrfeNh9QdNLw="
        file:
          - "client/build/jfx/native/DataAcquisitionClient.dmg"
        skip_cleanup: true
        on:
          tags: true
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - fakeroot
            - rpm
      script: ./gradlew clean assemble :client:jfxNative
      before_deploy:
        - export LINUX_DEB=$(ls client/build/jfx/native/dataacquisitionclient-*.deb)
      deploy:
        provider: releases
        api_key:
          secure: "kaF5Z4L9NjVqzjdY3GbyGMV2NgYLygkAf99qIPSrm3viUyNBmK+rVmZQuIA8y930fRPt7m0I2KmC1qIsAyVidiDX4MDFHg1b1m4BCwg63Z8s489E66wwOVOIuu+pOxiDONz4nyWTDHUQf/KQUnD3fzTg9nCDL69AYy/AF3v8C4T/GZyb9nLChnR5iM08SA8/rznlosQi6YDCebjX3oVY3jgbF2pZtuMDsznuDE4rEuXKXkK6Le+sp2yZtHjXnwOhBFiFWURhqnps1bJ8sKadaZxhhlcHdtB6frRjU7eNZDguq9cse20ayqpDOWZ47jL3GYZQ993blTFolSRcIb4uj+NJNJc0ujd7QOU+GVgir38T544m2/gXsn3emrlGVI/Jt08yv5QS/3+dXo7dW9z//0mWNucPiQeYIOfMG3C9LukYGKHv7Hy/nPDfsd3EiiwXgrzd85lAKLn6zvVNY1uUuDLxNR6X1Jru6trwTnJ1rX4r5+iVVOS0NJI6bYkoo5OwyZtG3E+McT6JfKZIscSo04Mwvxq2Wh/en03i5y41mrs6SEeBWSnEmIkx+hR2lkNeOIvU8JnPN5OIAxBiadQ713g6jlw1PwTV5hW+0rdetXkVAL1jtLgi9pnYnT8Q3Ayp2Iwltg1d2ClHwh26V5femrXEmDFJpNfmrfeNh9QdNLw="
        file:
          - "${LINUX_DEB}"
          - "server/build/distributions/server.zip"
          - "server/build/distributions/server.tar"
          - "log2csv/build/distributions/log2csv.zip"
          - "log2csv/build/distributions/log2csv.tar"
        skip_cleanup: true
        on:
          tags: true
